language: generic

dist: trusty
sudo: required

matrix:
    include:
    - os: linux
      compiler: gcc
      env: GCC_VERSION=7
        - CC=gcc-7
        - CXX=g++-7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'deadsnakes']
          packages: ['g++-7', 'python3.5']
          addons:

before_install:
  - export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"
  - |
    set -e
    set -x
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python3 get-pip.py
  - wget https://github.com/bazelbuild/bazel/releases/download/0.25.1/bazel_0.25.1-linux-x86_64.deb
  - sudo dpkg -i bazel_0.25.1-linux-x86_64.deb

install:
  # system libs
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran pkg-config unzip crossbuild-essential-armhf crossbuild-essential-arm64 build-essential
  # tensorflow deps
  - ./tensorflow/tensorflow/lite/tools/make/download_dependencies.sh

script:
  - pwd
  - ./tensorflow/tensorflow/lite/tools/make/build_rpi_lib.sh
  - ./tensorflow/tensorflow/lite/tools/make/build_aarch64_lib.sh
  - cd tensorflow && bazel build //tensorflow/lite/experimental/c:libtensorflowlite_c.so --crosstool_top=//external:android/crosstool --cpu=arm64-v8a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11"
