language: generic

dist: xenial
sudo: required

matrix:
    include:
    - os: linux
      compiler: gcc
      env: ARM=7=arm64-v8a
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['build-essential', 'python', 'wget', 'unzip', 'pkg-config']
          addons:

before_install:
  - |
    set -e
    set -x
  - wget https://github.com/bazelbuild/bazel/releases/download/0.25.1/bazel_0.25.1-linux-x86_64.deb
  - sudo dpkg -i bazel_0.25.1-linux-x86_64.deb

install:
  # system libs
  - sudo apt-get install crossbuild-essential-arm64
  # tensorflow deps
  - ./tensorflow/tensorflow/lite/tools/make/download_dependencies.sh

script:
  - pwd
  # ./tensorflow/tensorflow/lite/tools/make/build_aarch64_lib.sh
  - cd tensorflow && bazel build //tensorflow/lite/experimental/c:libtensorflowlite_c.so --crosstool_top=//external:android/crosstool --cpu=arm64-v8a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11"
